/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as StoreRouteImport } from './routes/store'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalUsersRouteImport } from './routes/portal/users'
import { Route as PortalReportsRouteImport } from './routes/portal/reports'
import { Route as PortalNotificationsRouteImport } from './routes/portal/notifications'
import { Route as PortalIncidentsRouteImport } from './routes/portal/incidents'
import { Route as PortalHierarchyRouteImport } from './routes/portal/hierarchy'
import { Route as PortalAssistantRouteImport } from './routes/portal/assistant'
import { Route as PortalAssetsRouteImport } from './routes/portal/assets'
import { Route as PortalAnalyticsRouteImport } from './routes/portal/analytics'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalUsersRoute = PortalUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalReportsRoute = PortalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalIncidentsRoute = PortalIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalHierarchyRoute = PortalHierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalAssistantRoute = PortalAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalAssetsRoute = PortalAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalAnalyticsRoute = PortalAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PortalRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/portal': typeof PortalRouteRouteWithChildren
  '/store': typeof StoreRoute
  '/workspace': typeof WorkspaceRoute
  '/api/chat': typeof ApiChatRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/assets': typeof PortalAssetsRoute
  '/portal/assistant': typeof PortalAssistantRoute
  '/portal/hierarchy': typeof PortalHierarchyRoute
  '/portal/incidents': typeof PortalIncidentsRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/users': typeof PortalUsersRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/store': typeof StoreRoute
  '/workspace': typeof WorkspaceRoute
  '/api/chat': typeof ApiChatRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/assets': typeof PortalAssetsRoute
  '/portal/assistant': typeof PortalAssistantRoute
  '/portal/hierarchy': typeof PortalHierarchyRoute
  '/portal/incidents': typeof PortalIncidentsRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/users': typeof PortalUsersRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/portal': typeof PortalRouteRouteWithChildren
  '/store': typeof StoreRoute
  '/workspace': typeof WorkspaceRoute
  '/api/chat': typeof ApiChatRoute
  '/portal/analytics': typeof PortalAnalyticsRoute
  '/portal/assets': typeof PortalAssetsRoute
  '/portal/assistant': typeof PortalAssistantRoute
  '/portal/hierarchy': typeof PortalHierarchyRoute
  '/portal/incidents': typeof PortalIncidentsRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/reports': typeof PortalReportsRoute
  '/portal/users': typeof PortalUsersRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/portal'
    | '/store'
    | '/workspace'
    | '/api/chat'
    | '/portal/analytics'
    | '/portal/assets'
    | '/portal/assistant'
    | '/portal/hierarchy'
    | '/portal/incidents'
    | '/portal/notifications'
    | '/portal/reports'
    | '/portal/users'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/store'
    | '/workspace'
    | '/api/chat'
    | '/portal/analytics'
    | '/portal/assets'
    | '/portal/assistant'
    | '/portal/hierarchy'
    | '/portal/incidents'
    | '/portal/notifications'
    | '/portal/reports'
    | '/portal/users'
    | '/portal'
  id:
    | '__root__'
    | '/portal'
    | '/store'
    | '/workspace'
    | '/api/chat'
    | '/portal/analytics'
    | '/portal/assets'
    | '/portal/assistant'
    | '/portal/hierarchy'
    | '/portal/incidents'
    | '/portal/notifications'
    | '/portal/reports'
    | '/portal/users'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  StoreRoute: typeof StoreRoute
  WorkspaceRoute: typeof WorkspaceRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/users': {
      id: '/portal/users'
      path: '/users'
      fullPath: '/portal/users'
      preLoaderRoute: typeof PortalUsersRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/reports': {
      id: '/portal/reports'
      path: '/reports'
      fullPath: '/portal/reports'
      preLoaderRoute: typeof PortalReportsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/incidents': {
      id: '/portal/incidents'
      path: '/incidents'
      fullPath: '/portal/incidents'
      preLoaderRoute: typeof PortalIncidentsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/hierarchy': {
      id: '/portal/hierarchy'
      path: '/hierarchy'
      fullPath: '/portal/hierarchy'
      preLoaderRoute: typeof PortalHierarchyRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/assistant': {
      id: '/portal/assistant'
      path: '/assistant'
      fullPath: '/portal/assistant'
      preLoaderRoute: typeof PortalAssistantRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/assets': {
      id: '/portal/assets'
      path: '/assets'
      fullPath: '/portal/assets'
      preLoaderRoute: typeof PortalAssetsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/analytics': {
      id: '/portal/analytics'
      path: '/analytics'
      fullPath: '/portal/analytics'
      preLoaderRoute: typeof PortalAnalyticsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteRouteChildren {
  PortalAnalyticsRoute: typeof PortalAnalyticsRoute
  PortalAssetsRoute: typeof PortalAssetsRoute
  PortalAssistantRoute: typeof PortalAssistantRoute
  PortalHierarchyRoute: typeof PortalHierarchyRoute
  PortalIncidentsRoute: typeof PortalIncidentsRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalReportsRoute: typeof PortalReportsRoute
  PortalUsersRoute: typeof PortalUsersRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalAnalyticsRoute: PortalAnalyticsRoute,
  PortalAssetsRoute: PortalAssetsRoute,
  PortalAssistantRoute: PortalAssistantRoute,
  PortalHierarchyRoute: PortalHierarchyRoute,
  PortalIncidentsRoute: PortalIncidentsRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalReportsRoute: PortalReportsRoute,
  PortalUsersRoute: PortalUsersRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PortalRouteRoute: PortalRouteRouteWithChildren,
  StoreRoute: StoreRoute,
  WorkspaceRoute: WorkspaceRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
