/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PortalRouteRouteImport } from './routes/portal/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalIncidentsRouteImport } from './routes/portal/incidents'
import { Route as PortalHierarchyRouteImport } from './routes/portal/hierarchy'
import { Route as PortalAssetsRouteImport } from './routes/portal/assets'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRouteRoute = PortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalIncidentsRoute = PortalIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalHierarchyRoute = PortalHierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => PortalRouteRoute,
} as any)
const PortalAssetsRoute = PortalAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => PortalRouteRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/store': typeof StoreRoute
  '/api/chat': typeof ApiChatRoute
  '/portal/assets': typeof PortalAssetsRoute
  '/portal/hierarchy': typeof PortalHierarchyRoute
  '/portal/incidents': typeof PortalIncidentsRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/store': typeof StoreRoute
  '/api/chat': typeof ApiChatRoute
  '/portal/assets': typeof PortalAssetsRoute
  '/portal/hierarchy': typeof PortalHierarchyRoute
  '/portal/incidents': typeof PortalIncidentsRoute
  '/portal': typeof PortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/portal': typeof PortalRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/store': typeof StoreRoute
  '/api/chat': typeof ApiChatRoute
  '/portal/assets': typeof PortalAssetsRoute
  '/portal/hierarchy': typeof PortalHierarchyRoute
  '/portal/incidents': typeof PortalIncidentsRoute
  '/portal/': typeof PortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/portal'
    | '/auth'
    | '/store'
    | '/api/chat'
    | '/portal/assets'
    | '/portal/hierarchy'
    | '/portal/incidents'
    | '/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/store'
    | '/api/chat'
    | '/portal/assets'
    | '/portal/hierarchy'
    | '/portal/incidents'
    | '/portal'
  id:
    | '__root__'
    | '/'
    | '/portal'
    | '/auth'
    | '/store'
    | '/api/chat'
    | '/portal/assets'
    | '/portal/hierarchy'
    | '/portal/incidents'
    | '/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRouteRoute: typeof PortalRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  StoreRoute: typeof StoreRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/incidents': {
      id: '/portal/incidents'
      path: '/incidents'
      fullPath: '/portal/incidents'
      preLoaderRoute: typeof PortalIncidentsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/hierarchy': {
      id: '/portal/hierarchy'
      path: '/hierarchy'
      fullPath: '/portal/hierarchy'
      preLoaderRoute: typeof PortalHierarchyRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/portal/assets': {
      id: '/portal/assets'
      path: '/assets'
      fullPath: '/portal/assets'
      preLoaderRoute: typeof PortalAssetsRouteImport
      parentRoute: typeof PortalRouteRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteRouteChildren {
  PortalAssetsRoute: typeof PortalAssetsRoute
  PortalHierarchyRoute: typeof PortalHierarchyRoute
  PortalIncidentsRoute: typeof PortalIncidentsRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteRouteChildren: PortalRouteRouteChildren = {
  PortalAssetsRoute: PortalAssetsRoute,
  PortalHierarchyRoute: PortalHierarchyRoute,
  PortalIncidentsRoute: PortalIncidentsRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteRouteWithChildren = PortalRouteRoute._addFileChildren(
  PortalRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRouteRoute: PortalRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  StoreRoute: StoreRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
